### ISSUE TITLE
Giraffe on Full Framework and Kestrel getting empty responses.

### ISSUE THREAD

**Issue by boeremak** [giraffe-fsharp/Giraffe#322] opened 2018-11-21 14:49 UTC
Hi,

I was having some trouble earlier on with Giraffe on the .Net 461 and Kestrel, but it never bothered me that much because I could use .Net Core. The problem is that I now do need a fix because of other libraries. Whenever I try to run Giraffe on VS 2017 it never returns any data. Chrome, will error out with `ERR_EMPTY_RESPONSE`. If I run the exact same code in VS Code and .Net Core it does work. 

This also happens when running Giraffe with the provided minimum code: https://github.com/giraffe-fsharp/Giraffe

Version: VS 2017 15.9.2
.Net 4.6.1
Giraffe: 3.4.0

Any ideas?

**Comment by dustinmoris** [comment] 2018-11-26 21:46
I have a Windows machine where I can test these scenarios. Could you create a minimalistic GitHub repo with a Giraffe app which only targets .NET 461 where you have issues to run it from VS 2017? I'll clone it then and try to find out what the issue is!

**Comment by boeremak** [comment] 2018-11-27 15:11
I'll see what I can do, installing the 4.7.2 Framework seems to fix it. I hope I can still reproduce it on another machine.

**Comment by boeremak** [comment] 2018-12-22 20:46
Do you need anything more from me? Happy to help.

**Comment by dustinmoris** [comment] 2020-06-28 10:38
I was never able to reproduce the issue on my old Windows machine. Given that we're dropping full framework support with the upcoming `5.0.0` release (inline with the upcoming .NET 5 release) I am inclined to close this issue.

.NET 5 will be the successor of all full framework monikers as well as all .NET Core monikers, so it's a single upgrade path for everyone which means the upcoming Giraffe release doesn't have to build against different frameworks anymore.

**Closed by dustinmoris** 2020-06-28 10:38 UTC
Labels: question, waiting response
