### ISSUE TITLE
Unexpected behaviour when calling async comp. expr. inside task comp. expr.

### ISSUE THREAD

**Issue by Micha-kun** [giraffe-fsharp/Giraffe#250] opened 2018-04-07 21:01 UTC
When mixing those comp. expr. and the async call is converted as task to be used with the task comp. expr. on the route execution function, the HttpContext parameter, unexpectedly, gets ServiceProvider property member marked as null, making json serialization breaks. Example:

```
let handlePostFiscalCompanyByCif =
        fun (next : HttpFunc)(ctx : HttpContext) ->
            task {
                let! msg = ctx.BindJsonAsync<FiscalCompanyByCifQuery>() // Ok
                let viewRepository = ctx.GetService<FiscalCompanyViewRepository>() // Ok
                // let! response = viewRepository.FindByCcc msg |> Async.StartAsTask <- This breaks
                let response = viewRepository.FindByCcc msg |> Async.RunSynchronously // <- this works
                match response with
                | Some data ->
                    return! Successful.ok (json data) next ctx // If uncomment the async code, 
                                                               // this breaks with Null exception
                | None ->
                    return! setStatusCode 204 next ctx
            }
```

Any help?

Thank you

**Comment by danieljsummers** [comment] 2018-07-19 22:01
I've run into issues mixing `Task` and `Async` (particularly around the injected per-request `DbContext`, which seems similar to the issue here). After the first time, I got an error saying that the context had been disposed.

I went back to full `Async` for that case, so I can't say how I fixed it. I've seen the issue, though. It may be related to `TaskBuilder` rather than Giraffe.

**Comment by dustinmoris** [comment] 2018-09-15 18:44
@Micha-kun @danieljsummers 
Hi, I really can't reproduce this issue and given that there has been not further update on this anymore I'm going to close this for now, but if this bug creeps up again then please try to capture as much info as possible and feel free to file it here again or in the TaskBuilder.fs repository if you think it is less of a Giraffe bug.

Sorry that I couldn't be of more help so far!

**Closed by dustinmoris** 2018-09-15 18:44 UTC
Labels: requires more info
