### ISSUE TITLE
Extract Giraffe.Tasks into separate NuGet package

### ISSUE THREAD

**Issue by forki** [giraffe-fsharp/Giraffe#143] opened 2017-11-16 06:47 UTC
Currently the task computation expression is bundled with the giraffe and therefore with full asp.net deps. But for libraries that I want to use in giraffe project and reuse on azure functions this is an issue.

**Comment by forki** [comment] 2017-11-16 06:47
If you are ok with separating both then I'm happy to send you a pull request

**Comment by nojaf** [comment] 2017-11-16 07:27
Duplicate of https://github.com/dustinmoris/Giraffe/issues/81?

**Comment by pblasucci** [comment] 2017-11-16 08:36
👍 for spining this out to its own package. I've got a few situations where that would be advantageous (nice work, by the way).

**Comment by forki** [comment] 2017-11-16 09:56
It's closed? Why?

Am 16.11.2017 08:27 schrieb "Florian Verdonck" <notifications@github.com>:

**Comment by nojaf** [comment] 2017-11-16 14:36
@forki did you know about https://github.com/fsharp/fslang-suggestions/issues/581?

**Comment by forki** [comment] 2017-11-16 14:53
This will take ages.
Extracting it into separate nuget will only take minutes

Am 16.11.2017 15:36 schrieb "Florian Verdonck" <notifications@github.com>:

**Comment by gerardtoconnor** [comment] 2017-11-16 15:17
Hi @forki 
This was originally kept separate due to attempted further optimizations on [TaskBuilder.fs](https://github.com/rspeele/TaskBuilder.fs) where, like in c# async/await we would avoid repeated memory allocations by having state as struct that re-use box ref in hibernation.

with https://github.com/fsharp/fslang-suggestions/issues/581 we can flesh out the particulars collectively on implementing as struct version in core library such that in the meantime, swapping to nuget of TaskBuilder.fs for giraffe should be fine (with just a few namespace changes etc).

**Comment by forki** [comment] 2017-11-16 19:19
Tbh I'm personally fine with current situation since I can use paket's
github dependencies to just include that single file. But I was wondering
if there is interest in a more general solution

Am 16.11.2017 16:17 schrieb "Gerard" <notifications@github.com>:

**Comment by dustinmoris** [comment] 2017-11-18 07:40
I'm still open to it and think it could be useful for people!

**Comment by dustinmoris** [comment] 2017-12-12 16:17
Done, latest Giraffe uses [Giraffe.Tasks](https://github.com/giraffe-fsharp/Giraffe.Tasks) from a NuGet package now.

**Comment by forki** [comment] 2017-12-12 16:17
Awesome. thanks
brb upgrading

2017-12-12 17:17 GMT+01:00 Dustin Moris Gorski <notifications@github.com>:

**Closed by dustinmoris** 2017-12-12 16:17 UTC
