### ISSUE TITLE
voidTag renders without  />

### ISSUE THREAD

**Issue by ITArchitectSebastianKJensen** [giraffe-fsharp/Giraffe#302] opened 2018-09-10 13:13 UTC
If I want to include a <script/>tag in the heading section of the HTML page, like

` <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"/>`

I create a new tag definition

`let scriptFile attr  =  voidTag "script" attr   `

and use this tag in my View definition

` scriptFile [ _src "https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js" ]`

When this tag is rendered the output is:

`<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js">`

it's missing the closing of the tag  /> or </script>. The lack of closing of the tag makes a error in the browser when rendering the html page

BR 
Sebastian

**Comment by dustinmoris** [comment] 2018-09-10 14:12
Hi,

The `<script>` tag must always have a closing `</script>`, which is why Giraffe has defined it as a `tag` and not as a `voidTag` element. If it were allowed to self close, then `<script>` without the `/>` would be sufficient according to the HTML spec.

For more info: https://stackoverflow.com/questions/69913/why-dont-self-closing-script-tags-work

**Comment by ITArchitectSebastianKJensen** [comment] 2018-09-10 17:06
Hi 
Yes you need to close the script tags with  /> OR </script>. (good point about not using />)

My problem with Giraffe is that I can´t close script tags without inline code.  I want to have a script tag in the HEAD section like this:

`<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>`

The code below is not accepted in the view definition, because a XmlNode list is expected.
 `script[ _src "https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js" ]` 

As you wrote would in your response, the code below is nor a option.
```
let scriptFile attr  =  voidTag "script" attr   
scriptFile[ _src "https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js" ]
```

What to do?
Br 
Sebastian

**Comment by dustinmoris** [comment] 2018-09-10 18:38
Ah ok now I see where the problem is :).

Just pass in an empty list if you don't have content between the tags:

```fsharp
script[ _src "https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js" ] []
```

Hope that helps ;)

**Comment by dustinmoris** [comment] 2018-09-13 18:08
Hi @ITArchitectSebastianKJensen I'm going to close this as I assume you got what you wanted, right?

**Closed by dustinmoris** 2018-09-13 18:08 UTC

**Comment by ITArchitectSebastianKJensen** [comment] 2018-09-14 06:57
Yes and thank you for the quick response
