### ISSUE TITLE
ReadBodyFromRequestAsync sometimes returns empty string even when body is not empty

### ISSUE THREAD

**Issue by cmeeren** [giraffe-fsharp/Giraffe#177] opened 2017-12-15 11:10 UTC
I'm experiencing a weird problem. When I use `ctx.ReadBodyFromRequestAsync()`, it will occasionally return empty string instead of the body I know for sure is there. I try the same request over and over again, and occasionally I get an empty string. See the images below - "ContentLength" indicates there is indeed content, but I get an empty string.

![contentlength](https://user-images.githubusercontent.com/7766733/34039724-f93cabea-e190-11e7-8405-a8faec4233fd.PNG)

![body](https://user-images.githubusercontent.com/7766733/34039726-f95a8cf0-e190-11e7-9aad-714395500ee7.PNG)

This seems to me a rather critical error.

**Comment by gerardtoconnor** [comment] 2017-12-15 11:56
Hi @cmeeren old friend 😄 
We have encountered fringe cases like this before where stream appears to be disposed of aggressively by asp.net core before properly read (or after an initial read).

In order to further look into this, can you provide any prior handlers in the pipeline before you try to read the body in the handler above?

It may be that something is triggering a read of body stream before this and disposing of the stream hence why header still showing content but body empty when you go to read.

**Comment by cmeeren** [comment] 2017-12-15 12:23
```f#
choose [
  ...
  route "/v4" >=> trackApiVersion "v4" >=> POST >=> handleV4
```

where `trackApiVersion` is defined like

```f#
let trackApiVersion (v:string) next ctx =
  trackEvent v
  next ctx
```

and `handleV4` calls `ReadBodyFromRequestAsync` on its first line.

**Comment by cmeeren** [comment] 2017-12-15 12:28
And as I said, this happens randomly, maybe 1 out of 10 times

**Comment by cmeeren** [comment] 2017-12-15 12:29
I also occasionally get a `NullReferenceException` on `ctx.ReadBodyFromRequestAsync()` instead of an empty body.

**Comment by cmeeren** [comment] 2017-12-15 12:53
Also note that I cannot reproduce the problem with `BindJsonAsync`. The reason I'm using `ReadBodyFromRequestAsync` and deserializing using `JsonConvert.DeserializeObject` is, as mentioned in #175, that my app and API communicates by sending shared, serialized objects (in an assembly referenced by both) back and forth, and I need to be sure that serialization and deserialization are compatible.

**Comment by dustinmoris** [comment] 2017-12-16 21:31
Ok so the only thing I noticed is that `BindJsonAsync` uses `deserializeJsonFromStream` from `Giraffe.Common` underneath and that function is reading from the `Stream` synchronously (which we should actually fix), so perhaps the async nature of `ReadBodyFromRequestAsync` is linked to this issue again similar to what we have seen in another issue before. This needs further investigation.

The [implementation of `ReadBodyFromRequestAsync`](https://github.com/giraffe-fsharp/Giraffe/blob/master/src/Giraffe/HttpContextExtensions.fs#L63-L66) is kept super simple, so my suggestion would be to check if we can reproduce the same intermittent issue with a plain ASP.NET Core app (without Giraffe) and implement a couple routes there which do essentially the same as your app now.

Since it seems to happen in relation to Async versions of reading the request body we could also test if the same Giraffe code would produce the same error with an [older version of Giraffe](https://github.com/giraffe-fsharp/Giraffe/releases/tag/v0.1.0-alpha025), before we introduced `task {}`.

**Comment by dustinmoris** [comment] 2017-12-21 16:16
@cmeeren Hey, we have had a bug fix in the `ReadBodyFromRequestAsync` method in the last release and wanted to double check if you can still reproduce the issue or if this has fixed it for you?

**Comment by dustinmoris** [comment] 2017-12-23 16:42
Closing now as this is believed to be fixed. Please reopen if you're still experiencing the same problem.

**Closed by dustinmoris** 2017-12-23 16:42 UTC
Labels: bug

**Comment by cmeeren** [comment] 2017-12-30 22:05
Unable to reproduce using latest nuget (0.1.0 beta 700). Thanks!

**Comment by forki** [comment] 2017-12-30 22:08
Yay!

Am 30.12.2017 23:05 schrieb "Christer van der Meeren" <
notifications@github.com>:
